### ISSUE TITLE
When a route is removed, the stops that were associated with that route become inaccessable.

### ISSUE THREAD

**Issue by jlyon1** [wtg/shuttletracker#77]

**Comment by jlyon1** [comment]
I feel like this represents a need for a fundamental change in the structure of how we store routes and stops. Routes should have a list of what stops they have, so we can handle things like this appropriately. 

I also plan to implement adding routes with all of their stops as a json file.

**Comment by kochman** [comment]
Agreed. We might take this opportunity to make sure we still want to use Mongo instead of a relational DB.

This leads me into another thought: both the East and West shuttle routes stop at the Union, and the Union stop should be the same entity in the database. But if the stops are all stored on the routes, then we'll have to have two Union stops. This might be okay, but it feels kludgy. Having relational data like this generally leads me toward Postgres...

**Comment by kench** [comment]
Old shuttle tracking developer here.  If you're looking for a relational database, Postgres is a really good bet.

Keep in mind that stops can belong to multiple routes.
